server:
  port: 8080

spring:
  application:
    name: product-trial
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=alten_store;encrypt=true;trustServerCertificate=true;
    username: alten
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2008Dialect
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE